### ISSUE TITLE
Enable single datetimepicker, not just range

### ISSUE THREAD

**Issue by andybaa** [SebastianRehfeldt/dash-datepicker#28]
Thank you for a great project! I believe it would be far more flexible and have tons of additional use-cases if you would add the flexibility option of only **showing one datetimepicker**, not only a range.

Is this something you could add? Hopefully, yes :)

Thanks,

**Comment by SebastianRehfeldt** [comment]
Hey @andybaa ,
I have built this dash component some time ago as I explicitly needed a datetime picker for a range of datetimes. For a single date + time it might be possible to use the standard dash components? I haven't worked much with dash in over a year and also did not plan to add any new features to this project. I'd be up for reviewing MRs though and will also update dependencies to fix eventual vulnerabilities in this package.

Some good news at the end :) The range component technically renders two single datetimepickers as you can see [here](https://github.com/SebastianRehfeldt/dash-datepicker/blob/master/dash_datetimepicker/src/lib/utils/DatePickerRange.jsx#L175). So it would be possible to modify the range component of this repo to only render one of them and to update the `onChange` functions. It would probably be easier and cleaner though to use the already existing single (react) datetimepicker and create a different dash component out of it. Instead of the range datepicker, it would be a different component `dash_datetimepicker.DashDatetimepickerSingle()`. Would that work as well?

**Comment by andybaa** [comment]
Hi @SebastianRehfeldt ,

Thank you for your response.

Adding a "dash_datetimepicker.DashDatetimepickerSingle()" would be just
perfect. In my use case I only need one component that includes date and
time, which the standard "dcc.DatePickerSingle" does not. This is where
dash_datetimepicker was very interesting. I need to run this dash app on a
touch tablet, and as such your datetimepicker enables up/down arrows for
time, eliminating the need for writing.

I have no experience with neither react nor the boilerplate functionality
of dash, so I do not know if it would be easier to do the one from the
other. However, I agree that a dash version of the react-library would be a
perfect match and provide a greater flexibility for the module.

**Comment by SebastianRehfeldt** [comment]
Alright :)
I am also neither a React nor dash developer, but wrapping the react component into dash boilerplate was not too much effort. So I will give it another try and add the single component as discussed. I have only exposed a subset of the react properties to dash which you can find here: https://github.com/SebastianRehfeldt/dash-datepicker/blob/master/dash_datetimepicker/src/lib/components/DashDatetimepicker.react.js#L45

I'd go with the same set of properties for the single component. We can add more properties when more are needed.

**Comment by andybaa** [comment]
Great!
I would say that the current datetimepicker properties should be enough as a start:
'id', 'locale', 'Date', 'utc'
Thanks

**Comment by SebastianRehfeldt** [comment]
Hey! I had some time today to checkout the single datepicker. I am no react developer which is why I had some troubles. But seems that I got it to work. Feel free to give it a try: `pip install dash-datetimepicker==0.0.7` and report bugs if you find some.

You can find the MR here: https://github.com/SebastianRehfeldt/dash-datepicker/pull/30
